import os
import sys
import markdown
from datetime import datetime
from dotenv import load_dotenv

# Add project root to sys path
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(BASE_DIR)

from src.agent.mcp import send_gmail_email

def get_html_template(content_html: str) -> str:
    """Wrap the HTML content in a beautiful, styled template."""
    timestamp = datetime.now().strftime("%B %d, %Y")
    
    return f"""
    <html>
      <head>
        <style>
          body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: #f4f7f6;
            margin: 0;
            padding: 20px;
            color: #333333;
          }}
          .container {{
            max-width: 1400px;
            width: 95%;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 12px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.05);
            overflow: hidden;
          }}
          .header {{
            background: linear-gradient(135deg, #6366f1, #4f46e5);
            color: white;
            padding: 30px 20px;
            text-align: center;
          }}
          .header h1 {{
            margin: 0;
            font-size: 24px;
            font-weight: 600;
          }}
          .header p {{
            margin: 10px 0 0;
            font-size: 14px;
            opacity: 0.9;
          }}
          .content {{
            padding: 30px;
            line-height: 1.6;
          }}
          .content h2 {{
            color: #4f46e5;
            font-size: 20px;
            margin-top: 25px;
            padding-bottom: 10px;
            border-bottom: 1px solid #e5e7eb;
          }}
          .content h3 {{
            color: #4f46e5;
            font-size: 18px;
            margin-top: 25px;
            margin-bottom: 15px;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 8px;
          }}
          .content ul {{
            padding-left: 20px;
          }}
          .content li {{
            margin-bottom: 8px;
          }}
          .content blockquote {{
            border-left: 4px solid #ef4444;
            background-color: #fef2f2;
            margin: 20px 0;
            padding: 15px 20px;
            color: #7f1d1d;
            font-style: italic;
            border-radius: 0 8px 8px 0;
          }}
          .footer {{
            background-color: #f9fafb;
            padding: 20px;
            text-align: center;
            font-size: 12px;
            color: #6b7280;
            border-top: 1px solid #e5e7eb;
          }}
          .button {{
            display: inline-block;
            background-color: #4f46e5;
            color: white;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 6px;
            font-weight: bold;
            margin-top: 20px;
          }}
          .grid-container {{
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            gap: 25px;
            justify-content: center;
          }}
          .grid-item {{
            flex: 1;
            min-width: 320px;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 10px;
            border: 1px solid #e5e7eb;
            box-shadow: 0 2px 4px rgba(0,0,0,0.02);
            box-sizing: border-box;
          }}
          @media (max-width: 900px) {{
            .grid-container {{
              flex-direction: column;
            }}
          }}
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Weekly App Review Insights</h1>
            <p>{timestamp} • AI-Generated Executive Summary</p>
          </div>
          <div class="content">
            {content_html}
            <div style="text-align: center; margin-top: 30px;">
              <p>Explore the full data on your interactive dashboard:</p>
              <a href="#" class="button">View Dashboard</a>
            </div>
          </div>
          <div class="footer">
            <p>This report was automatically generated by the App Review Insights Analyzer pipeline.</p>
          </div>
        </div>
      </body>
    </html>
    """

def main():
    # Load env vars
    load_dotenv(os.path.join(BASE_DIR, '.env'))
    
    data_dir = os.path.join(BASE_DIR, 'data')
    report_path = os.path.join(data_dir, 'weekly_report.md')
    
    if not os.path.exists(report_path):
        print(f"Error: Report file not found at {report_path}")
        return
        
    print("Loading generated report...")
    with open(report_path, 'r', encoding='utf-8') as f:
        report_content = f.read()
        
    print("Converting markdown to styled HTML...")
    import re
    # Split the markdown into sections separated by ###
    parts = re.split(r'(?=\n### )', "\n" + report_content)
    
    html_parts = []
    for part in parts:
        if part.strip():
            html_parts.append(f'<div class="grid-item">{markdown.markdown(part.strip())}</div>')
            
    content_html = f'<div class="grid-container">{"".join(html_parts)}</div>'
    
    # Wrap in our dashboard-like template
    final_html = get_html_template(content_html)
    
    to_email = os.environ.get("MCP_GMAIL_TO")
    subject = os.environ.get("MCP_GMAIL_SUBJECT")
    
    if not to_email or not subject:
        print("Error: MCP_GMAIL_TO or MCP_GMAIL_SUBJECT environment variables are missing.")
        return
        
    print(f"Sending HTML email to {to_email}...")
    
    # The MCP tool expects token.json to be in current directory
    cwd = os.getcwd()
    try:
        mcp_server_dir = os.path.join(BASE_DIR, 'mcp-server')
        os.chdir(mcp_server_dir)
        result = send_gmail_email(to_email, subject, final_html, is_html=True)
        print("Gmail API Result:", result)
    except Exception as e:
        print(f"Error sending Gmail email: {e}")
    finally:
        os.chdir(cwd)

if __name__ == "__main__":
    main()
